### ISSUE TITLE
experimental data

### ISSUE THREAD

**Issue by myd1** [rajkstats/AOL-Exploratory-Data-Analysis#1]
Hello, may I ask if the experimental data can be provided? Thank you

**Comment by rajkstats** [comment]
Sure, I will update the repo soon with all links.

**Comment by myd1** [comment]
thank you wery much.

**Comment by rajkstats** [comment]
Link to dataset : http://www.cim.mcgill.ca/~dudek/206/Logs/AOL-user-ct-collection/user-ct-test-collection-02.txt.gz
